### ISSUE TITLE
[dependencies] Relax dependency on starlette

### ISSUE THREAD

**Issue by Arpafaucon** [auredentan/starlette-session#3]
Hi @auredentan, and thank you for this package ! I was able to seamlessly replace starlette's builtin `SessionMiddleware` by yours in a matter of minutes, this is fantastic !

I have a small problem, though: version 0.4.1 requires `starlette` version to  `>=0.13.8` and `<0.14`, which is not compatible with the more recent versions I have in production (`fastapi==70.0`, who requires `starlette==0.16`).

I was wondering: would it be possible to relax this dependency constraint ? From what I've read on starlette change notes, I don't see anything blocking, and so far tests on my machine are going well.

EDIT : I see that you already committed such a change on master ^^ perfect for me! May I ask when you plan to release your next version?

**Comment by auredentan** [comment]
Hi,

Yes I did forget to release the changes on pypi, that's done on 0.4.2 now.

Hope it helps.
